name: Build nginx

on:
  push:
    tags:
      - 'v*'

env:
  NGINX_VERSION: '1.25.2'

jobs:
  create_release:
    runs-on: ubuntu-22.04
    outputs:
      upload_url: ${{ steps.set_upload_url.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v2

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Set upload URL
        id: set_upload_url
        env:
          url: ${{ steps.create_release.outputs.upload_url }}
        run: |
          url=${url%%\{*}
          echo "upload_url=$url" >> $GITHUB_OUTPUT

  build:
    needs: create_release
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - os: 'Debian 12'
            dockerfile: './bookworm.Dockerfile'
          - os: 'Ubuntu 22.04'
            dockerfile: './jammy.Dockerfile'
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build for ${{ matrix.os }}
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          outputs: |
            type=image,push=false
          build-args: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
            UPLOAD_URL=${{ needs.create_release.outputs.upload_url }}
            NGINX_VERSION=${{ env.NGINX_VERSION }}
          file: ${{ matrix.dockerfile }}
