name: Build NGINX

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          ./workflow.sh
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload results
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          url: ${{ steps.create_release.outputs.upload_url }}
        run: |
          url=${url%%\{*}
          ver=1.23.1
          file=nginx.tar.xz
          name="nginx-$ver-linux-x86_64.tar.xz"
          url="$url?name=$name"
          curl -f -X POST -D - \
                -H "Authorization: token $token" \
                -H 'Accept: application/vnd.github.v3+json' \
                -H 'Content-Type: application/x-xz' \
                --data-binary "@$file" \
                "$url"
